#!/usr/bin/env php
<?php

require __DIR__."/vendor/autoload.php";

/**
 * Make Config instance
 */
$config =  \Rufus\Console\Config::instance()->init();


/**
 * Create console instance
 */
$console = new \Rufus\Console\Console($config);

/**
 * Load the custom command application
 */
require __DIR__.'/routes/console.php';

/**
 * Start console
 */
$console->run();